### ISSUE TITLE
Installer does not copy UmbracoCommerceCheckout folder to App_Plugins

### ISSUE THREAD

**Issue by pageorge** [umbraco/Umbraco.Commerce.Checkout#1] opened 2023-09-07 16:12 UTC
We are running Umbraco.Cms 10.5.1 with: Vendr 2.4.1, Vendr.Checkout 2.1.2, Vendr.PaymentProviders.PayPal" 2.0.1, Vendr.PaymentProviders.Stripe 2.0.1, Vendr.uSync 2.0.1.

After following the upgrade to Umbraco Commerce instructions on https://docs.umbraco.com/umbraco-commerce/how-to-guides/migrate-from-vendr-to-umbraco-commerce. When it came to installing Umbraco.Commerce.Checkout 10.0.0, the Settings page shows [ucc] and clicking it gives a 404 not found: /App_Plugins/UmbracoCommerceCheckout/backoffice/views/dashboards/installer.html so we could not install the new node/doc types/data types. Someone else reported the same issue on the Umbraco forum with no reply: https://our.umbraco.com/forum/using-umbraco-and-getting-started/112485-umbraco-commerce-and-umbraco-commerce-checkout-checkout-dashboard-throwing-errors

As this was blocking us from upgrading I tried building and publishing the support\10.x branch and manually copying \bin\Release\net6.0\publish\wwwroot (excluding App_Plugins\Umbraco.Licenses) to our App_Plugins folder and the Umbraco Commerce Checkout menu then appears, we could then click the Install button and the new ucc nodes/doc types/datatypes get created. All working fine from then on!

Thought I'd mention this in case there's an issue with the nuget package copying in to the App_Plugins folder or if this is now all done in C#....

Cheers
Phil

**Comment by mattbrailsford** [comment] 2023-09-08 12:29
The new Umbraco Commerce Checkout packages should be RCLs and so don’t distribute files on disk. It sounds like there could be an issue in v10 it not managing to resolve these. 

I’ll take a look 👍🏻

**Comment by mattbrailsford** [comment] 2023-09-12 14:36
Ok, I think I found the issue. I think our build script wasn't quite updated properly when setting up the v10 build and so it wasn't actually embedding the static assets in the nuget file. I've updated this now and it appears they are now there. If you fancied testing this out, I've pushed a build to Umbraco's nightly feed 10.0.1--preview.6 if you wanted to try it out https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install/installing-nightly-builds

**Comment by mattbrailsford** [comment] 2023-09-14 08:14
Fixed in 10.0.1

**Closed by mattbrailsford** 2023-09-14 08:14 UTC

**Comment by robertjf** [comment] 2023-10-17 06:08
@mattbrailsford I'm seeing the same problem with Commerce 12.1.1 and Commerce.Checkout 12.0.0...

**Comment by mattbrailsford** [comment] 2023-10-17 07:24
@robertjf just to be clear, are you saying the dashboards etc in the back aren't displaying? or that the static assets just aren't on disk? The later is expected behavior due to the use of RCLs

**Comment by mattbrailsford** [comment] 2023-10-17 07:35
What OS are you running on?

**Comment by robertjf** [comment] 2023-10-17 07:46
MacOS - Here's what appears to be missing (this is the front-end):
<img width="842" alt="image" src="https://github.com/umbraco/Umbraco.Commerce.Checkout/assets/818101/04afda1e-6fe0-426f-b710-d01651d9772e">

**Comment by mattbrailsford** [comment] 2023-10-17 07:47
Then bingo, I think that could be the issue. It looks like the path in the templates is set to `/app_plugins/umbracocommercecheckout/...` when it should be `/App_Plugins/UmbracoCommerceCheckout/...` so with MacOS being case sensitive, this will probably be why it's not being found.

**Comment by robertjf** [comment] 2023-10-17 07:48
Aaaah - of course!

**Comment by mattbrailsford** [comment] 2023-10-17 07:49
Lemme create a new build and I'll push it to our nightly feed for you to try out

**Comment by mattbrailsford** [comment] 2023-10-17 07:54
Ok, there should be a 12.0.1 preview on the nightly feed now https://www.myget.org/F/umbraconightly/api/v3/index.json

**Comment by robertjf** [comment] 2023-10-17 09:28
Thanks @mattbrailsford  - that's fixed it :)

**Comment by mattbrailsford** [comment] 2023-10-17 09:34
Perfect. I'll get an update posted out soon.

**Comment by mattbrailsford** [comment] 2025-03-05 15:14
Are your running on a mac / Linux?

**Comment by ccasalicchio** [comment] 2025-03-05 18:28
Matt, I'm running it on Windows.

I have "installed" Checkout again and recreated all the pages. Now, the checkout shows 404. What am I missing?

![Image](https://github.com/user-attachments/assets/1afb47d4-b239-43d6-a7bc-e0194c86ef0d)

![Image](https://github.com/user-attachments/assets/4dc62b78-f46c-49b4-8004-6ee72d2e5754)

**Comment by mattbrailsford** [comment] 2025-03-06 08:17
You shouldn’t need to assign a template as it should do this automatically if there isn’t one set. 

I’m not quite sure why it’s not picking them up though. Best I could suggest is if you pulled the source code and debug into the template resolution code to see why it’s not triggering 

https://github.com/umbraco/Umbraco.Commerce.Checkout/blob/main/src/Umbraco.Commerce.Checkout/Web/Controllers/UmbracoCommerceCheckoutCheckoutStepPageController.cs#L33
